# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - jouny

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # --- CHANGE #1: ADDED WORKING DIRECTORY ---
      # This tells the runner to execute these commands inside your app's subfolder,
      # where the package.json file is located.
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: ./JOURNY # Assuming your subfolder is named 'JOURNY' based on the error log

      # --- CHANGE #2: UPDATED ARTIFACT PATH ---
      # This ensures that only the contents of your application folder are
      # uploaded, not the entire repository. This is crucial for the deploy job.
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./JOURNY # Upload only the app's folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_95CFC3610C814F7CBBF816F229673EEA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DD7BC93F069F4C5E818C8A574BB3D075 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7EA2BFEFDCEB421F85E8F1A63711B4A7 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'jouny'
          slot-name: 'Production'
          package: .
